import type { Metadata } from 'next'
import { Rubik, Silkscreen } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

const rubik = Rubik({
   weight: "400",
   subsets: ["latin"],
   variable: "--font-HachiMaruPop",
});
const silkscreen = Silkscreen({
   weight: "400",
   subsets: ["latin"],
   variable: "--font-RampartOne",
});


export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="ja">
         <head>
            <title>PG Clock</title>
      <link rel="shortcut icon" href="./static/favicon.ico"/>
         </head>
         <body className={'${Rubik.variable} ${Rubik.variable} font-Rubik'}>
            {children}
         </body>
      </html>
   )
}
